### ISSUE TITLE
[Bug]: <insert title here>

### ISSUE THREAD

**Issue by httom111** [microsoft/live-share-sdk#633]
**Describe the bug**

Cannot start the 01.dice-roller example in live-share-sdk\samples\javascript\01.dice-roller.
When npm start the example, always get error message:
[plugin:vite:import-analysis] Failed to resolve entry for package "@microsoft/live-share". The package may have incorrect main/module/exports specified in its package.json.
C:/Users/asus/Documents/GitHub/live-share-sdk/samples/javascript/01.dice-roller/src/app.js
    at packageEntryFailure (file:///C:/Users/asus/Documents/GitHub/live-share-sdk/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
    at resolvePackageEntry (file:///C:/Users/asus/Documents/GitHub/live-share-sdk/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23379:5)
    at tryNodeResolve (file:///C:/Users/asus/Documents/GitHub/live-share-sdk/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
    at Context.resolveId (file:///C:/Users/asus/Documents/GitHub/live-share-sdk/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
    at async Object.resolveId (file:///C:/Users/asus/Documents/GitHub/live-share-sdk/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:32)
    at async TransformContext.resolve (file:///C:/Users/asus/Documents/GitHub/live-share-sdk/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42575:23)
    at async normalizeUrl (file:///C:/Users/asus/Documents/GitHub/live-share-sdk/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40500:34)
    at async file:///C:/Users/asus/Documents/GitHub/live-share-sdk/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40651:47
    at async Promise.all (index 0)
    at async TransformContext.transform (file:///C:/Users/asus/Documents/GitHub/live-share-sdk/node_modules/vite/d

I try to set server.hmr.overlay to false in vite.config.js. But this error message still exits.
**To Reproduce**
https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/teams-live-share-quick-start

**Screenshots**
<img width="758" alt="image" src="https://github.com/microsoft/live-share-sdk/assets/72293978/54c5e3dc-0bc8-451c-aadf-8a3c0ca507ad">

**Desktop(s) (please complete the following information):**

- OS: [Windows]
- npm: 9.6.6
- nodejs:20.2.0

**Comment by httom111** [comment]
Thank you, I got it done. I just followed the instructions on that webpage and didn’t see that there is a guideline here. Thank you very much.
